from .llm import llm_with_tools
from langchain_core.messages import HumanMessage
from src.ccoe_ai.tools.embedding_tool import generate_embedding_from_excel
import os
import pandas as pd
import structlog

logger = structlog.get_logger(__name__)


def invoke_embedding_agent(data: dict) -> dict:
    normalized_path = data["normalized_path"]
    output_path = data["output_path"]
    logger.info(
        "invoke_embedding_agent",
        normalized_path=normalized_path,
        output_path=output_path,
    )

    # Natural-language task handed to the agent
    task_message = HumanMessage(
        content=(
            f"Generate embeddings for the Excel file at {normalized_path} and save the result to {output_path}."
        )
    )

    # LLM reasons about the task and emits tool_calls
    ai_message = llm_with_tools.invoke([task_message])
    logger.debug(
        "llm_response_received",
        tool_calls=getattr(ai_message, "tool_calls", None),
        content=getattr(ai_message, "content", None),
    )

    parquet_path = output_path  # fallback

    # execute the tool calls emitted by the LLM agent
    # for tool_call in ai_message.tool_calls:
    #     tool_name = tool_call["name"]
    #     tool_args = tool_call["args"]
    #     logger.debug(
    #         "tool_call_received",
    #         tool_name=tool_name,
    #         tool_args=tool_args,
    #     )
    #
    #     if tool_name == generate_embedding_from_excel.name:
    #         logger.info(
    #             "calling_embedding_tool",
    #             tool_name=tool_name,
    #         )
    #         result = generate_embedding_from_excel.invoke(tool_args)
    #         parquet_path = result

    if not ai_message.tool_calls:
        logger.warning("LLM didn't use the tool. Manually invoke tools.")
        generate_embedding_from_excel.invoke(
            {
                "input_path": data["normalized_path"],
                "output_path": data["output_path"],
            }
        )
    else:
        # Executing the tool call generated by LLM
        for tool_call in ai_message.tool_calls:
            tool_name = tool_call["name"]
            tool_args = tool_call["args"]
            logger.debug(
                "tool_call_received",
                tool_name=tool_name,
                tool_args=tool_args,
            )
            generate_embedding_from_excel.invoke(tool_call["args"])
    return {"parquet_path": parquet_path}


def load_embeddings(data: dict) -> dict:
    logger.debug("load_embedding_start")
    df = pd.read_parquet(data["parquet_path"])

    # Completely remove unnecessary columns to prevent excessive data weight from causing LLM encoding issues.
    name_col = "Full Name" if "Full Name" in df.columns else df.columns[0]
    email_col = "Email" if "Email" in df.columns else df.columns[1]

    # Handle illegal line breaks to prevent CSV misalignment.
    clean_df = df.dropna(subset=[name_col, email_col], how="all")

    cols_to_drop = ["embedding", "vector", "combined_text", "similarity_score"]
    clean_df = clean_df.drop(
        columns=[c for c in cols_to_drop if c in clean_df.columns], errors="ignore"
    )

    clean_df = clean_df.replace(r"[\n\r]", " ", regex=True)

    target_dir = "data"
    os.makedirs(target_dir, exist_ok=True)
    final_path = os.path.join(target_dir, "deduplicated_final.xlsx")

    clean_df.to_excel(final_path, index=False, engine="openpyxl")

    logger.info(
        "load_embeddings_end",
        cleaned_data_row=len(clean_df),
        output_path=final_path,
    )

    # Only show the first 50 lines to the LLM for auditing to prevent garbled characters from appearing in the response due to excessive length.
    return {"data": clean_df.head(50).to_markdown()}
